### ISSUE TITLE
Tracing methods with complex types as arguments

### ISSUE THREAD

**Issue by Andersonfn** [alfredxiao/jackplay#5]
Hi,

Thank you very much for the app. Very clever thing. 

I traced sucessfully methods with simple type as arguments, like String and Integers, but when I try to trace methods with another objects as arguments the jackplay says  that cannot find the argument class .

is that the normal behaviour? how to set the classpath for achieve that?

Thank you very much.

**Comment by alfredxiao** [comment]
Hi Andersonfn, 
Apology that I missed notification from this issue. Wonder if you still have problem with that. If yes, could you let me know how your use case is? Is it in defaultTrace setting in command line argument, or is it in when you try to add a trace (on a method that takes a custom class type as argument) from the UI?
Regards,
Alfred

**Comment by alfredxiao** [comment]
Tried a custom class as parameter works when tracing, the `demo-java` has function like `myapp.greeter.QAGreeter.testArguments(boolean,byte,short,int,long,float,double,char,java.lang.String,java.lang.Object,myapp.greeter.QAGreeter,java.lang.String[],byte[],int[])` which is traceable. So closing this issue.
